/**
 * Bridge module for importing HL7 messages from various formats.
 *
 * Provides functions to convert JSON, YAML, and TOML back to HL7 pipe-delimited
 * format. The input should match the structure produced by the export functions.
 *
 * Use cases:
 * - Re-importing messages that were exported and modified externally
 * - Loading messages generated by external tools in JSON/YAML/TOML format
 * - Round-tripping for version control (export → edit → import)
 *
 * Expected input structure:
 * - Segments → object keys (arrays represent repeated segments)
 * - Fields → 1-based string indices (MSH.1 = "|", MSH.2 = "^~\\&")
 * - Components → 1-based indices; simple strings for single-component fields
 * - Field repetitions → arrays
 *
 * Note: MSH field "1" (field separator) is skipped during import since it's
 * implicit in the pipe-delimited output. Delimiters are extracted from MSH
 * field "2" (encoding characters).
 *
 * @example
 * // JSON input:
 * // {
 * //   "MSH": {
 * //     "1": "|",
 * //     "2": "^~\\&",
 * //     "3": "APP",
 * //     "7": "20231215",
 * //     "9": { "1": "ADT", "2": "A01" }
 * //   }
 * // }
 * // Output: MSH|^~\&|APP|||20231215||ADT^A01
 */

import { invoke } from "@tauri-apps/api/core";

/**
 * Imports an HL7 message from JSON format.
 *
 * @param content - The JSON-formatted message content
 * @returns The message as pipe-delimited HL7 text
 */
export async function importFromJson(content: string): Promise<string> {
  return invoke<string>("import_from_json", { content });
}

/**
 * Imports an HL7 message from YAML format.
 *
 * @param content - The YAML-formatted message content
 * @returns The message as pipe-delimited HL7 text
 */
export async function importFromYaml(content: string): Promise<string> {
  return invoke<string>("import_from_yaml", { content });
}

/**
 * Imports an HL7 message from TOML format.
 *
 * @param content - The TOML-formatted message content
 * @returns The message as pipe-delimited HL7 text
 */
export async function importFromToml(content: string): Promise<string> {
  return invoke<string>("import_from_toml", { content });
}
